apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  annotations:
    apps.tanzu.vmware.com/promotable: ""
    apps.tanzu.vmware.com/promote-group: ContainerApp/single-image-single-app
  creationTimestamp: null
  name: single-image-single-app.apps.local.20240712.1712.54705
spec:
  refName: single-image-single-app.apps.local
  releasedAt: "2024-07-12T17:16:43Z"
  template:
    spec:
      deploy:
      - kapp:
          rawOptions:
          - --wait=false
      fetch:
      - imgpkgBundle:
          image: us-west1-docker.pkg.dev/app-last-mile/nwebb/tanzu-platform-catalog@sha256:24d626235b8ac0c329a6e6cf4df77e1aed18f56daf37bba907ecf7c1cd1ada96
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
  valuesSchema:
    openAPIv3: null
  version: 20240712.1712.54705
